//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalacticRentalsADOModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charge
    {
        public int chargeId { get; set; }
        public int clientId { get; set; }
        public string chargeType { get; set; }
        public System.DateTime chargeDate { get; set; }
        public decimal amount { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
