//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalacticRentalsADOModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Charges = new HashSet<Charge>();
            this.Rentals = new HashSet<Rental>();
        }
    
        public int clientId { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string addressCity { get; set; }
        public string addressPostCode { get; set; }
        public byte[] image { get; set; }
        public Nullable<bool> active { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<Charge> Charges { get; set; }
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
