//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalacticRentalsADOModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.DVDItems = new HashSet<DVDItem>();
        }
    
        public int movieId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public byte[] image { get; set; }
        public string stars { get; set; }
        public string ageRestriction { get; set; }
        public string director { get; set; }
    
        public virtual ICollection<DVDItem> DVDItems { get; set; }
    }
}
